import argparse
import pandas as pd
import numpy as np
import faiss
import json
import time
import os
from sentence_transformers import SentenceTransformer
from huggingface_hub import hf_hub_download
from llama_cpp import Llama

def run_pipeline(candidates_path, output_path):
    start_time = time.time()
    print("Initiating Redrob AI Ranker Pipeline...")

    # --- 1. LOAD ARTIFACTS ---
    # In production, these artifacts are generated by Phase 1 and stored alongside this script.
    base_dir = os.path.dirname(os.path.abspath(__file__))
    INDEX_PATH = os.path.join(base_dir, 'candidate_index.faiss')
    META_PATH = os.path.join(base_dir, 'candidate_metadata.csv')
    
    if not os.path.exists(INDEX_PATH) or not os.path.exists(META_PATH):
        raise FileNotFoundError("Pre-computed FAISS index or metadata CSV not found. Run Phase 1 first.")

    index = faiss.read_index(INDEX_PATH)
    metadata_df = pd.read_csv(META_PATH)

    # --- 2. VECTORIZE JOB DESCRIPTION ---
    jd_text = """
    Senior AI Engineer. Deep technical depth in modern ML systems: embeddings, retrieval, ranking, LLMs, fine-tuning. 
    Production experience with embeddings-based retrieval systems (sentence-transformers, BGE).
    Production experience with vector databases or hybrid search infrastructure.
    Strong Python. Evaluation frameworks for ranking systems.
    """
    embed_model = SentenceTransformer('all-MiniLM-L6-v2')
    jd_vector = embed_model.encode([jd_text]).astype('float32')
    faiss.normalize_L2(jd_vector)

    # --- 3. SEMANTIC RECALL ---
    # Retrieve top 2000 initially. If the input file is small (sandbox mode), it handles it gracefully.
    RECALL_K = min(2000, len(metadata_df))
    distances, indices = index.search(jd_vector, RECALL_K)
    
    recall_df = metadata_df.iloc[indices[0]].copy()
    recall_df['semantic_score'] = distances[0]
    recall_df['composite_score'] = recall_df['semantic_score'] * recall_df['behavioral_multiplier']
    
    # Drop known honeypots flagged in Phase 1
    recall_df = recall_df[recall_df['is_honeypot_flag'] == 0]

    # --- 4. HARD DISQUALIFICATIONS (Parsing Input File) ---
    candidate_ids_to_check = set(recall_df['candidate_id'].tolist())
    candidate_details = {}
    
    # Read the provided candidates file (could be 100k or a small 50-candidate sandbox sample)
    with open(candidates_path, 'r', encoding='utf-8') as file:
        for line in file:
            cand = json.loads(line.strip())
            c_id = cand.get('candidate_id')
            if c_id in candidate_ids_to_check:
                profile = cand.get('profile', {})
                history = cand.get('career_history', [])
                companies = [h.get('company', '').lower() for h in history]
                
                # We also extract reasoning facts here to save a second read pass
                skills = [s.get('name', '') for s in cand.get('skills', []) if isinstance(s, dict)]
                
                candidate_details[c_id] = {
                    "companies": companies,
                    "title": profile.get('current_title', 'Unknown'),
                    "experience": profile.get('years_of_experience', 0),
                    "skills": ", ".join(skills[:3])
                }

    CONSULTANCIES = {'tcs', 'infosys', 'wipro', 'accenture', 'cognizant', 'capgemini'}
    RESEARCH_TERMS = {'lab', 'university', 'research', 'academic', 'institute'}

    def is_disqualified(c_id):
        companies = candidate_details.get(c_id, {}).get('companies', [])
        if not companies: return False
        if all(any(cons in comp for cons in CONSULTANCIES) for comp in companies): return True
        if all(any(res in comp for res in RESEARCH_TERMS) for comp in companies): return True
        return False

    recall_df['is_disqualified'] = recall_df['candidate_id'].apply(is_disqualified)
    final_pool = recall_df[recall_df['is_disqualified'] == False].copy()

    # Sort and handle deterministic tie-breaking [cite: 176]
    final_pool = final_pool.sort_values(by=['composite_score', 'candidate_id'], ascending=[False, True])
    
    # Isolate top 100 (or less if sandbox sample is small)
    top_100 = final_pool.head(100).copy()

    # Normalize scores 0.70 to 0.99
    max_score, min_score = top_100['composite_score'].max(), top_100['composite_score'].min()
    if max_score > min_score:
        top_100['composite_score'] = ((top_100['composite_score'] - min_score) / (max_score - min_score)) * 0.29 + 0.70
    
    top_100['rank'] = range(1, len(top_100) + 1)

    # --- 5. REASONING GENERATION ---
    print("Loading LLM for Reasoning Generation...")
    model_path = hf_hub_download(repo_id="Qwen/Qwen1.5-0.5B-Chat-GGUF", filename="qwen1_5-0_5b-chat-q4_k_m.gguf")
    llm = Llama(model_path=model_path, n_ctx=512, n_threads=4, verbose=False)

    reasonings = []
    for _, row in top_100.iterrows():
        c_id = row['candidate_id']
        facts = candidate_details.get(c_id, {"title": "Engineer", "experience": 5, "skills": "AI"})
        
        prompt = f"""<|im_start|>system
You are a technical recruiter. Write exactly one short sentence explaining why this candidate is a good fit. Use ONLY the provided facts. Do not hallucinate.
<|im_end|>
<|im_start|>user
Facts: Title: {facts['title']}, Experience: {facts['experience']} years, Key Skills: {facts['skills']}.
<|im_end|>
<|im_start|>assistant
"""
        output = llm(prompt, max_tokens=40, temperature=0.3, stop=["<|im_end|>"])
        reasonings.append(output['choices'][0]['text'].strip().replace("\n", " "))

    top_100['reasoning'] = reasonings

    # --- 6. FORMAT & EXPORT ---
    submission_df = top_100[['candidate_id', 'rank', 'composite_score', 'reasoning']].copy()
    submission_df.rename(columns={'composite_score': 'score'}, inplace=True)
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    submission_df.to_csv(output_path, index=False)
    
    elapsed = time.time() - start_time
    print(f"Pipeline complete in {elapsed:.2f} seconds. Output saved to {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Redrob Candidate Ranker")
    parser.add_argument("--candidates", required=True, help="Path to candidates.jsonl file")
    parser.add_argument("--out", required=True, help="Path to output submission.csv file")
    
    args = parser.parse_args()
    run_pipeline(args.candidates, args.out)